apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: chat-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: chat-app/frontend:latest
        ports:
        - containerPort: 3006
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.chat.example.com"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: chat-app
spec:
  selector:
    app: frontend
  ports:
  - port: 3006
    targetPort: 3006
  type: LoadBalancer
